### ISSUE TITLE
Can't understand DDA algorithm implementation

### ISSUE THREAD

**Issue by defpis** [andrewlowndes/perfect-antialiasing#3]
First of all, thank you very much for creating this project, I learned a lot from it 👍👍👍.
Several demo codes are easy to understand, but when I saw the dda algorithm, I was very confused.
I searched the implementation of the dda algorithm, it seems very simple, the code is as follows:

![image](https://user-images.githubusercontent.com/48018016/124860505-59f99b00-dfe4-11eb-8f71-1cd9eb17635b.png)
![image](https://user-images.githubusercontent.com/48018016/124860561-6bdb3e00-dfe4-11eb-97b5-f691c1377d9f.png)

Why are the algorithms in the project so different, what are the differences between them, and how to understand this code
```
export const dda = (p1: Point, p2: Point, opts: DdaOptions, cb: (cellPos: Point) => boolean | void) => {
    const dir = normalize(sub(p2, p1));
    const relativePos = sub(p1, opts.pos);
    const cellPos = floor(divide(relativePos, opts.cellSize));
    const tDelta = abs(divide(opts.cellSize, dir));
    const step = sign(dir);
    const distToClosestCell = multiply(opts.cellSize, add(cellPos, sign(adds(step, 1))));
    const tMax = divide(sub(distToClosestCell, relativePos), dir);
    const stopCell = floor(divide(sub(p2, opts.pos), opts.cellSize));
    
    for (let i = 0; i < opts.maxSteps; i++) {
        if (opts.min && opts.max && !inRange(cellPos, opts.min, opts.max)) {
            return true;
        }
        if (cb(cellPos) === false) {
            return false;
        }
        if (equal(stopCell, cellPos)) {
            return true;
        }
        if (tMax.x < tMax.y) {
            tMax.x += tDelta.x;
            cellPos.x += step.x;
        }
        else {
            tMax.y += tDelta.y;
            cellPos.y += step.y;
        }
    }
    return true;
};
```
Any help would be greatly appreciated!

**Comment by andrewlowndes** [comment]
I understand the confusion, I think the names need refactoring, it is actually a modified DDA algorithm (designed to visit each pixel the line crosses) - based on this approach: http://www.cse.yorku.ca/~amana/research/grid.pdf

Note: I have created a more heavily-tested version (but in Rust) here: https://github.com/andrewlowndes/texture-filtering/blob/main/rust_generator/src/dda.rs - I am planning to migrate this back to Typescript soon, along with the Rust version of the scanline algorithm to improve the efficiency of the cpu rasteriser parts of this project.

**Comment by defpis** [comment]
Thanks @andrewlowndes
